version: 2

sources:
  - name: raw
    database: blockstream
    schema: raw
    description: "Raw data extracted from external APIs"
    tables:
      - name: raw_binance_us_24hr_ticker
        description: "Raw 24hr ticker statistics from Binance.US API"
        columns:
          - name: id
            description: "Date identifier (YYYYMMDD format)"
            tests:
              - not_null
              - unique
          - name: raw_response
            description: "JSON array of ticker data from API"
            tests:
              - not_null
              - test_raw_response_not_blank
        loaded_at_field: created_at
        freshness:
          warn_after: { count: 1, period: day }
          error_after: { count: 2, period: day }

models:
  - name: stg__binance_us_24hr_ticker
    description: >
      Cleaned and typed 24hr ticker data from Binance.US API. 
      Each record represents one symbol's daily price metrics with data quality flags.
    config:
      tags: ["staging", "crypto", "binance"]
    columns:
      - name: record_date
        description: "Date identifier from source extraction (YYYYMMDD)"
        tests:
          - not_null

      - name: symbol
        description: "Trading pair symbol (e.g., BTCUSD, ETHUSD)"
        tests:
          - not_null

      - name: price_change
        description: "Absolute price change in USD over 24hr window"
        tests:
          - not_null

      - name: price_change_percent
        description: "Percentage price change over 24hr window"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: -99.99
              max_value: 10000.0

      - name: last_price
        description: "Most recent trade price in USD"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0.000001
              max_value: 10000000

      - name: high_price
        description: "Highest price during 24hr window"
        tests:
          - not_null

      - name: low_price
        description: "Lowest price during 24hr window"
        tests:
          - not_null

      - name: volume
        description: "Total base asset volume traded in 24hr"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: quote_volume
        description: "Total quote asset (USD) volume traded in 24hr"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: trade_count
        description: "Number of individual trades in 24hr window"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: bid_price
        description: "Current highest bid price"
        tests:
          - not_null

      - name: ask_price
        description: "Current lowest ask price"
        tests:
          - not_null

      - name: spread_percentage
        description: "Bid-ask spread as percentage of last price"

      - name: data_quality_score
        description: "Data quality score from 0-1 (1 = perfect quality)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true

    tests:
      - unique:
          column_name: "symbol || record_date"
      - test_price_direction
      - test_chronology
      - test_trade_id_order

  - name: int__ticker_rolling_metrics
    description: >
      Rolling financial metrics calculated over 7, 14, and 28 day windows.
      Includes volatility, momentum, liquidity indicators and market rankings.
    config:
      tags: ["intermediate", "crypto", "analytics"]
    columns:
      - name: symbol
        description: "Trading pair symbol"
        tests:
          - not_null

      - name: record_date
        description: "Date of the metrics calculation"
        tests:
          - not_null

      - name: last_price_avg_7d
        description: "7-day rolling average of last price"

      - name: last_price_stddev_7d
        description: "7-day rolling standard deviation of last price (volatility)"

      - name: volume_sum_7d
        description: "7-day cumulative trading volume"

      - name: pct_change_7d
        description: "Price change vs 7-day average as percentage"

      - name: liquidity_ratio
        description: "Volume to price ratio indicating liquidity depth"

      - name: rank_price_increase_7d
        description: "Ranking by 7-day price performance (1 = best performer)"

      - name: rank_volatility_7d
        description: "Ranking by 7-day volatility (1 = most volatile)"

    tests:
      - unique:
          column_name: "symbol || record_date"

  - name: fact__daily_ticker_summary
    description: >
      Analytics-ready daily summary combining core metrics with rolling indicators.
      One row per symbol per day with comprehensive crypto market analytics.
    config:
      tags: ["mart", "crypto", "analytics"]
      materialized: "table"
    columns:
      - name: date_key
        description: "Date in YYYY-MM-DD format"
        tests:
          - not_null

      - name: symbol
        description: "Trading pair symbol"
        tests:
          - not_null

      - name: price_usd
        description: "Closing price in USD"
        tests:
          - not_null

      - name: daily_return_pct
        description: "Daily return percentage"

      - name: volatility_7d
        description: "7-day rolling volatility"

      - name: volume_usd_24h
        description: "24-hour USD trading volume"

      - name: market_cap_rank
        description: "Daily ranking by market activity"

    tests:
      - unique:
          column_name: "symbol || date_key"

  - name: dim__cryptocurrency
    description: >
      Slowly changing dimension table for cryptocurrency metadata.
      Tracks symbol lifecycle, classification, and enrichment data.
    config:
      tags: ["dimension", "crypto"]
    columns:
      - name: symbol
        description: "Trading pair symbol (natural key)"
        tests:
          - not_null
          - unique

      - name: base_asset
        description: "Base cryptocurrency (e.g., BTC, ETH)"

      - name: quote_asset
        description: "Quote currency (typically USD)"

      - name: first_seen_date
        description: "First date this symbol appeared in our data"

      - name: last_seen_date
        description: "Most recent date this symbol appeared"

      - name: is_active
        description: "Whether symbol is currently actively trading"

      - name: asset_category
        description: "Classification: major, altcoin, stablecoin, etc."

  - name: meta__data_quality_summary
    description: >
      Daily data quality metrics and monitoring indicators.
      Tracks completeness, accuracy, and pipeline health.
    config:
      tags: ["meta", "monitoring"]
    columns:
      - name: check_date
        description: "Date of quality assessment"
        tests:
          - not_null

      - name: total_symbols
        description: "Count of unique symbols processed"

      - name: avg_data_quality_score
        description: "Average quality score across all symbols"

      - name: records_with_anomalies
        description: "Count of records flagged with data anomalies"

      - name: pipeline_status
        description: "Overall pipeline health: healthy, warning, error"
