name: Daily Binance.US Extraction

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download DuckDB artifact (if exists)
        uses: actions/download-artifact@v3
        with:
          name: blockstream-duckdb
          path: data
        continue-on-error: true # First run may not have artifact, so don’t fail

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run extraction script
        run: |
          source venv/bin/activate
          python /scripts/extract.py

      - name: Upload DuckDB artifact
        uses: actions/upload-artifact@v3
        with:
          name: blockstream-duckdb
          path: data/blockstream.duckdb
